version: '3.7'

x-var: &APP_IMAGE_TAG
  "application-name:1.0.0"
x-var: &RUBY_VERSION
  "3.0.1"
x-var: &RAILS_VERSION
  6.1.2
x-var: &PG_MAJOR
  11
x-var: &POSTGRES
  "postgres:11"
x-var: &NODE_MAJOR
  12
x-var: &YARN_VERSION
  1.13.0
x-var: &BUNDLER_VERSION
  2.0.2
x-var: &DATABASE_HOST
  "postgres"
x-var: &DATABASE_USER
  "postgres"
x-var: &DATABASE_PASSWORD
  "postgres"
x-var: &REDIS_URL
  "redis://redis:6379"
x-rails-app: &rails-app
  build:
    context: .
    dockerfile: ./.dockerdev/rails-psql/Dockerfile
    args:
      RUBY_VERSION: *RUBY_VERSION
      RAILS_VERSION: *RAILS_VERSION
      PG_MAJOR: *PG_MAJOR
      NODE_MAJOR: *NODE_MAJOR
      YARN_VERSION: *YARN_VERSION
      BUNDLER_VERSION: *BUNDLER_VERSION
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
  image: *APP_IMAGE_TAG
  tmpfs:
    - /tmp

x-rails-backend: &rails-backend
  <<: *rails-app
  stdin_open: true
  tty: true
  volumes:
    - ./rails:/app:cached
    - bundle:/bundle
    - ./rails/node_modules:/app/node_modules:cached
    - packs:/app/public/packs
    - rails_cache:/app/tmp/cache
    - .dockerdev/.psqlrc:/root/.psqlrc:ro
    - .dockerdev/.bashrc:/root/.bashrc:ro
  environment:
    <<: *env
    DATABASE_HOST: *DATABASE_HOST
    DATABASE_USER: *DATABASE_USER
    DATABASE_PASSWORD: *DATABASE_PASSWORD
    BOOTSNAP_CACHE_DIR: /bundle/_bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    REDIS_URL: *REDIS_URL
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: *POSTGRES
    volumes:
      - ./.dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_DB: postgres
      POSTGRES_USER: *DATABASE_USER
      POSTGRES_PASSWORD: *DATABASE_PASSWORD
    ports:
      - 5432
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

  rails-backend:
    <<: *rails-backend

  runner:
    <<: *rails-backend
    command: /bin/bash

  rails-server:
    <<: *rails-backend
    command: bundle exec foreman start
    ports:
      - '3000:3000'

  sidekiq:
    <<: *rails-backend
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:

  